import type { Metadata } from "next";
import "./globals.scss";
import ReduxProvider from "@/store/redux-provider";
import Header from "@/components/header/header";
import Menu from "@/components/menu/Menu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <Header />
          <Menu />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
