import type { Metadata } from "next";
import "./globals.scss";
import { ReactNode } from "react";
import Header from "@/components/navigation/header/header";
import Footer from "@/components/navigation/footer/Footer";
import Menu from "@/components/navigation/menu/Menu";
import ReduxProvider from "@/store/redux-provider";
import ModalHandler from "@/components/UI/modals/modal-handler";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <Header />
          <Menu />
          <ModalHandler />
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
